name: nlp_app
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - spacy
  - spacy-model-en_core_web_sm
  - pip
  - pip:
      - streamlit
  
  
  
 
